### ISSUE TITLE
Setup SQLite extension

### ISSUE THREAD

**Issue by vidbina** [Suprnovae/abc-totaal-notitieblok#3]
We need to have https://github.com/andpor/react-native-sqlite-storage set up for Android and iOS. Please deliver at least one separate commit per todo :wink: which should make cherry-picking easy, if needed at a later stage.
# TODO
- [x] Setup SQLite for iOS
- [ ] Test `CREATE_TABLE` for table `records` with the fields:
  - `description STRING`
  - `description STRING`
  - `category STRING`
  - `attachment STRING`
  - `value_cents BIGINT` stores all monetary values in cents in order to eliminate rounding errors that may surface when floats are used (with 32 bit integers this should set us up for at most 4294967295 cent units which should work for currencies that aren't inflated like crazy)
  - `value_currency CHAR(3)` in [ISO 4217:2015](https://en.wikipedia.org/wiki/ISO_4217) (use the string `EUR` for euros, `USD` for US dollars and `XTS` as a test currency)
  - `datetime_string CHAR(29)` in [ISO 8601](http://www.w3.org/TR/NOTE-datetime) which should allow us to save a localised time
  - `datetime_epoch DATETIME DEFAULT CURRENT_TIMESTAMP` automatically saves the elapsed seconds since epoch
- [ ] Test `INSERT` and `UPDATE` queries on a single example from the [records sample set](https://github.com/Suprnovae/abc-totaal-notitieblok/wiki/Records)
- [x] Setup SQLite for Android

**Comment by vidbina** [comment]
Deliver all commits into the `setup/sqlite` branch. Try to commit everything for iOS separately and everything for Android separately as well.
